"""Refresh phish_domains.feed.txt from free public blocklists.

Downloads known-bad domains and writes them one per line to
phish_domains.feed.txt, which the analyzer unions with your own phish_domains.txt
at startup. This is the only part of the project that goes online, and the
analyzer never runs it; run it yourself when you want fresh data:

    python update_feeds.py

Standard library only. Sources (all free, no API key):
  - abuse.ch URLhaus            https://urlhaus.abuse.ch/downloads/text_online/
  - Phishing.Database (ACTIVE)  https://github.com/mitchellkrogza/Phishing.Database
  - Phishing.Army               https://phishing.army/

Hosts whose domain is in feed_exclude.txt (major legit sites) are dropped, so a
bad feed entry can't turn the blocklist against google.com and friends.
"""
import datetime
import os
import re
import sys
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(HERE, 'phish_domains.feed.txt')
EXCLUDE_PATH = os.path.join(HERE, 'feed_exclude.txt')

FEEDS = [
    ('Phishing.Database (ACTIVE)',
     'https://raw.githubusercontent.com/mitchellkrogza/'
     'Phishing.Database/master/phishing-domains-ACTIVE.txt',
     'domains'),
    ('Phishing.Army blocklist',
     'https://phishing.army/download/phishing_army_blocklist.txt',
     'domains'),
    ('abuse.ch URLhaus (online)',
     'https://urlhaus.abuse.ch/downloads/text_online/',
     'urls'),
]

# Drop raw IPs; the analyzer flags those on its own.
_IP_RE = re.compile(r'^(?:\d{1,3}(?:\.\d{1,3}){3}|0x[0-9a-f]+|\d{6,})$', re.I)
_HOST_RE = re.compile(r'^[a-z0-9.-]+\.[a-z]{2,}$')

TIMEOUT = 60
MAX_DOWNLOAD = 64 * 1024 * 1024  # refuse a feed that balloons past this
UA = 'phish-analyzer-update-feeds/1.0 (+https://github.com/RyanSecEng/phish-analyzer)'


def _fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        data = resp.read(MAX_DOWNLOAD + 1)
    if len(data) > MAX_DOWNLOAD:
        raise ValueError(f"feed exceeds {MAX_DOWNLOAD} bytes; refusing")
    return data.decode('utf-8', 'replace')


def _hosts_from_domains(text):
    for line in text.splitlines():
        line = line.split('#', 1)[0].strip().lower().strip('.')
        if line:
            yield line


def _hosts_from_urls(text):
    for line in text.splitlines():
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        host = urllib.parse.urlparse(line).hostname
        if host:
            yield host.lower().strip('.')


def _load_exclude():
    """Major legit domains to keep out of the feed (host == d or *.d)."""
    excl = set()
    try:
        with open(EXCLUDE_PATH, encoding='utf-8') as fh:
            for line in fh:
                line = line.split('#', 1)[0].strip().lower().strip('.')
                if line:
                    excl.add(line)
    except OSError:
        pass
    return excl


def _excluded(host, excl):
    return any(host == d or host.endswith('.' + d) for d in excl)


def main():
    exclude = _load_exclude()
    domains = set()
    skipped = 0
    errors = []
    for name, url, kind in FEEDS:
        print(f"[*] {name}\n    {url}")
        try:
            text = _fetch(url)
        except Exception as exc:  # one feed failing shouldn't sink the rest
            print(f"    [WARN] skipped: {type(exc).__name__}: {exc}")
            errors.append(name)
            continue
        extract = _hosts_from_domains if kind == 'domains' else _hosts_from_urls
        before = len(domains)
        for host in extract(text):
            if _IP_RE.match(host) or not _HOST_RE.match(host):
                continue
            if exclude and _excluded(host, exclude):
                skipped += 1
                continue
            domains.add(host)
        print(f"    added {len(domains) - before} new hosts "
              f"({len(domains)} total)")

    if not domains:
        print("\n[ERROR] No domains fetched from any feed; leaving "
              "phish_domains.feed.txt unchanged.")
        return 1

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        '%Y-%m-%dT%H:%M:%SZ')
    header = (
        "# phish_domains.feed.txt - AUTO-GENERATED by update_feeds.py.\n"
        "# Do not edit by hand and do not commit: it is large and changes daily.\n"
        "# Put your own permanent entries in phish_domains.txt instead.\n"
        f"# generated: {stamp}\n"
        f"# {len(domains)} hosts from: "
        + ", ".join(n for n, _, _ in FEEDS) + "\n")
    with open(OUT_PATH, 'w', encoding='utf-8') as fh:
        fh.write(header)
        for host in sorted(domains):
            fh.write(host + "\n")

    print(f"\n[OK] Wrote {len(domains)} hosts to {OUT_PATH}")
    if exclude:
        print(f"[OK] Excluded {skipped} hosts on major legit domains "
              f"({len(exclude)} guard entries).")
    if errors:
        print(f"[NOTE] {len(errors)} feed(s) failed: {', '.join(errors)}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
